# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56d4e235042c26a92d01b354003646daf81341d2b7a22765203c3ed0df9485a6c21fe2b070fa3c1d910af526d3443ab31a6ac707b83ee970938ab5bb7849c622

test:
  secret_key_base: f22f7470f7d1f2cf9b116589ad299ce06f01d039c27a30104763f6ff48c5310c0b0eb9eaad54859d09806334f6b631f342ac9832f033c29c9f09a60d7d1890b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
